services:
  api:
    build: .
    container_name: compose-api
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: compose-redis
    volumes:
      - redis-data:/data

volumes:
  redis-data: